spring:
    profiles:
        active: dev
        
---
spring:
    profiles: dev
    application: 
        name: sprigcloud-config-dev

---
spring:
    profiles: test
    application: 
        name: sprigcloud-config-test